import localFont from "next/font/local";
import Head from "next/head";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Newsletter from "@/components/Newsletter";
import StickyBar from "@/components/StickyBar";
import InstagramBoxes from "@/components/InstagramBoxes"

const OpenSansRegular = localFont({
  src: "./fonts/OpenSansCondensed-Regular.woff", 
  variable: "--font-open-sans-regular", 
  weight: "400"
})

const OpenSansSemiBold = localFont({
  src: "./fonts/OpenSansCondensed-SemiBold.woff", 
  variable: "--font-open-sans-semibold", 
  weight: "600"
})

const OpenSansBold = localFont({
  src: "./fonts/OpenSansCondensed-Bold.woff", 
  variable: "--font-open-sans-bold", 
  weight: "700"
})

const Poppins = localFont({
  src: "./fonts/Poppins-Bold.woff", 
  variable: "--font-poppins-bold", 
  weight: "700"
})

const Lora = localFont({
  src: "./fonts/Lora-Italic.woff", 
  variable: "--font-lora-italic", 
  weight: "400"
})

const Updock = localFont({
  src: "./fonts/Updock-Regular.woff", 
  variable: "--font-updock", 
  weight: "600"
})

export const metadata = {
  title: "Carlsen Ekstra",
  description: "Generated by Freja and Daniela",
};

export default function RootLayout({ children }) {
  return (
    <html lang="da">
      <body
        className={`${OpenSansRegular.variable} ${OpenSansSemiBold.variable} ${OpenSansBold.variable} ${Poppins.variable} ${Lora.variable} ${Updock.variable} antialiased pt-12`}
      >
        <StickyBar/>
        <Header/>
          {children}
          <InstagramBoxes />
        <Newsletter/>
        <Footer/>
      </body>
    </html>
  );
}
